version: '3.8'

services:
  db:
    image: postgres:15
    container_name: flask_orders_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: flask_orders
    ports:
      - "6565:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - orders-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_orders_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:123456@db:5432/flask_orders
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - SQLALCHEMY_ECHO=False
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - orders-network

volumes:
  pgdata:

networks:
  orders-network:
    driver: bridge